name:                 heap-sort
version:              0.1.0.0
visibility:           public
id:                   heap-sort-0.1.0.0-inplace
key:                  heap-sort-0.1.0.0-inplace
license:              MIT
maintainer:           artem@example.com
author:               Artem
synopsis:             Пірамідальне сортування на Haskell
description:          Реалізація heap sort з використанням рекурсії
category:             Algorithms
abi:                  inplace
exposed:              True
exposed-modules:      HeapSort
import-dirs:
    /mnt/c/Users/user/Desktop/Exam/dist-newstyle/build/x86_64-linux/ghc-9.6.7/heap-sort-0.1.0.0/build

library-dirs:
    /mnt/c/Users/user/Desktop/Exam/dist-newstyle/build/x86_64-linux/ghc-9.6.7/heap-sort-0.1.0.0/build

library-dirs-static:
    /mnt/c/Users/user/Desktop/Exam/dist-newstyle/build/x86_64-linux/ghc-9.6.7/heap-sort-0.1.0.0/build

dynamic-library-dirs:
    /mnt/c/Users/user/Desktop/Exam/dist-newstyle/build/x86_64-linux/ghc-9.6.7/heap-sort-0.1.0.0/build

data-dir:             /mnt/c/Users/user/Desktop/Exam/.
hs-libraries:         HSheap-sort-0.1.0.0-inplace
depends:              base-4.18.3.0
haddock-interfaces:
    /mnt/c/Users/user/Desktop/Exam/dist-newstyle/build/x86_64-linux/ghc-9.6.7/heap-sort-0.1.0.0/doc/html/heap-sort/heap-sort.haddock

haddock-html:
    /mnt/c/Users/user/Desktop/Exam/dist-newstyle/build/x86_64-linux/ghc-9.6.7/heap-sort-0.1.0.0/doc/html/heap-sort
